core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='item_list'),
    path('account_info/<slug>/', account_info.as_view(), name='profile'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_item', add_item, name='add'),
    path('delete_item/<id>', delete_item, name='delete' )
]

decommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify 
from annoying.fields import AutoOneToOneField
from django.utils import timezone

CATEGORY_CHOICES = (
    ('E', 'Electronics'),
    ('F', 'Fashion'),
    ('HAB', 'Health and Beauty'),
    ('HAG', 'House and Garden'),
    ('S', 'Sports'),
    ('A', 'Auto'),
    ('O', 'Others')
)

class Location(models.Model):
    region = models.CharField(max_length=29)
    area = models.CharField(max_length=25)
    city = models.CharField(max_length=27)
    street = models.CharField(max_length=132)


    def __str__(self):
        return '%s, %s' % (self.city, self.street)


class Item(models.Model):
    img = models.ImageField(upload_to='images/', default='/images/default.jpg')
    title = models.CharField(max_length=100)
    price = models.FloatField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post_date = models.DateTimeField(default=timezone.now) 
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField()
    location = models.OneToOneField(Location, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super(Item, self).save(*args, **kwargs)
        self.slug = slugify('product'+str(self.id))
        super(Item, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={"slug": self.slug})

class Profile(models.Model):
    user = AutoOneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)
    
    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse("core:profile", kwargs={"slug": self.slug})

core/forms.py
from allauth.account.forms import SignupForm
from django import forms
from .models import Item, Location
from django.utils.translation import gettext_lazy as _
 
class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
 
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['img', 'title', 'price', 'category', 'description']
        labels = {
            'img': _('Изображение'),
            'title': _('Название'),
            'price': _('Цена'),
            'category': _('Категория'),
            'description': _('Описание'),
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = '__all__'
        labels = {
            'region': _('Регион'),
            'area': _('Район'),
            'city': _('Город'),
            'street': _('Улица')
        }

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Item, Profile
from .forms import ItemForm, AddressForm

def is_valid_queryparam(param):
    return param != '' and param is not None

class HomeView(ListView):
    model = Item
    paginate_by = 4
    template_name = "home.html"


    def get_queryset(self):
        cat_query = self.request.GET.get('category')
        query = self.request.GET.get('q')
        object_list = Item.objects.all()
        if is_valid_queryparam(query):        
            object_list = object_list.filter(title__icontains=query)
        if is_valid_queryparam(cat_query) and cat_query != 'Choose..':
            object_list = object_list.filter(category=cat_query)
        return object_list


class account_info(DetailView):
    model = Profile
    template_name = 'account_info.html'

class ItemDetailView(DetailView):
    model = Item
    template_name = 'product.html'

def add_item(request):
    if request.method == 'POST':
        item_form = ItemForm(request.POST)
        address_form = AddressForm(request.POST)
        if all((item_form.is_valid(), address_form.is_valid())):
            address = address_form.save()
            item = item_form.save(commit=False) 
            item.img = request.FILES.get('img', 'images/default.jpg')
            item.location = address
            item.user = request.user
            item.save()
            return redirect('core:home')
    else:
        item_form = ItemForm()
        address_form = AddressForm()
    context = {
        'items': Item.objects.all(),
        'item_form': item_form,
        'address_form': address_form
    }
    return render(request, 'item_create.html', context)

def delete_item(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return redirect('core:home')

templates/account_info.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row d-flex">
        <div>
            <div class="ms-3" style="margin-top: 100px; ">
                <h5>Личная информация:</h5>
                <p>Имя: {{profile.user.first_name}}</p>
                <p>Фамилия: {{profile.user.last_name}}</p>
                <p>Электронная почта: {{profile.user.email}}</p>
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">Товары:</p>
            </div>
            <section class="text-center mb-4">
                <div class="row wow fadeIn">
                {% for item in profile.user.item_set.all %}
                  <div class ="col-lg-3 col-md-6 mb-4">
                    <div class="card">
                      <div class="view overlay">
                        <img height="250" src="/media/{{ item.img }}" class="card-img-top" alt="">
                        <a href="{{ item.get_absolute_url }}">
                          <div class="mask rgba-white-slight"></div>
                        </a>
                      </div>
                      <div class="card-body text-center">
                        <a href="" class="grey-text">
                          <h5>{{ item.get_category_display }}</h5>
                        </a>
                        <h5>
                          <strong>
                            <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                          </strong>
                        </h5>
                        <h4 class="font-weight-bold blue-text">
                          <strong>{{ item.price }}</strong>
                          <span>&#8381;</span>
                        </h4>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
            </section>
        </div>
    </div>
  </div>
{%endblock%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

{% include "navbar.html" %}

<body>
    {% block content  %}
    {% endblock content %}

    {% include "scripts.html" %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <main class='mt-5 pt-4'>
    <div class="container">
    <form id = "myForm" method="GET" action=".">
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">
        <span class="navbar-brand">Категории:</span>
        <!-- Collapsible content -->
        <div class="container-fluid">
          <!-- Links -->
          <a class="navbar-brand">
                <select id="category" class="form-control" name="category" onChange="this.form.submit();">
                  <option value="Choose..">Choose..</option>
                  <option value="E">Electronics</option>
                  <option value="F">Fashion</option>
                  <option value="HAB">Health and Beauty</option>
                  <option value="HAG">House and Garden</option>
                  <option value="S">Sports</option>
                  <option value="A">Auto</option>
                  <option value="O">Others</option>
                </select>
          </a>
          <form class="d-flex" method="GET" action=".">
            <div class="form-inline md-form my-0">
              <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="q">
            </div>
          </form>
        </div>
      </nav>
    </form>
      <section class="text-center mb-4">
        <div class="row wow fadeIn">
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
              <div class="view overlay">
                <img height='250' src="/media/{{ item.img }}" class="card-img-top"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                  </strong>
                </h5>
                <h4 class="font-weight-bold blue-text">
                  <strong>{{ item.price }}</strong>
                  <span>&#8381;</span>
                </h4>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </section>
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% else %}
            <li class="page-item  disabled">
              <a class="page-link" disabled href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
          {% endif %}
          {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item">
                <a class="page-link href="#""> {{ i }} </a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}    
        </ul>
      </nav>
      {% endif %}
    </div>
  </main>
  {% endblock content %}

templates/item_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="form-group mt-5 pt-4">
            <form method="POST" action="{% url 'core:add' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ item_form|crispy }}
                {{ address_form|crispy }}
                <button class="btn btn-primary" type="submit">Добавить</button>
            </form>
        </div>
    </div>
{%endblock%}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">E-commerce</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'core:add' %}">
                <span class="clearfix d-none d-sm-inline-block"> Добавить товар </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{{ user.profile.get_absolute_url }}">
                <span class="clearfix d-none d-sm-inline-block text-uppercase"> {{ user.username }} </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clearfix d-none d-sm-inline-block"> Выйти </span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clearfix d-none d-sm-inline-block"> Войти </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                <span class="clearfix d-none d-sm-inline-block"> Регистрация </span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

templates/product.html
{% extends "base.html" %}

{% block content %}
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">
            <div class="row wow fadeIn">
                <div class="col-md-6 mb-4">
                    <img src="/media/{{ object.img }}" class="img-fluid" alt="" width='500'>
                </div>
                <div class="col-md-6 mb-4">
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">{{ object.get_category_display }}</span>
                        </a>
                    </div>
                    <p class="lead">
                        <span class="font-weight-bold">Название:</span>
                        <span>{{ object.title }}</span>
                    </p>
                    <p class="lead">
                        <span class="font-weight-bold">Продавец:</span>
                        <span><a href='{{ item.user.profile.get_absolute_url }}'>{{item.user.username}}</a></span>
                    </p>
                    <p class="lead">
                        <span class="font-weight-bold">Адрес:</span>
                        <span>{{item.location.region}}, {{item.location.area}} район, {{item.location.city}}, ул.{{item.location.street}}</a></span>
                    </p>
                    <p class="lead">
                        <span class="font-weight-bold">Цена:</span>
                        <span> {{ object.price }}</span>
                        <span>&#8381;</span>
                    </p>
                    <p class="lead">
                        <span class="font-weight-bold">Дата добавления:</span>
                        <span>{{item.post_date}}</a></span>
                    </p>
                    <p class="lead font-weight-bold">Описание</p>
                    <p>{{ object.description }}</p>
                    {%if request.user.is_authenticated and user.username == item.user.username%}
                        <form method='POST'>
                            <p class="lead">
                                <a href={% url 'core:delete' item.id %} class='btn btn-danger'>Удалить</a>
                            </p>
                        </form>
                    {%endif%}
                </div>
                </div>
            </div>
            <hr>
            <div class="row d-flex wow fadeIn">
                <div class="text-left">
                <h4 class="my-4 h4">Информация о продавце</h4>
                <p>Имя пользователя: <a href='{{ item.user.profile.get_absolute_url }}'>{{item.user.username}}</a></p>
                <p>Имя: {{item.user.first_name}}</p>
                <p>Фамилия: {{item.user.last_name}}</p>
                <p>Электронная почта: {{item.user.email}}</p>
                </div>
            </div>
        </div>
    </main>

  
{% endblock content %}

templates/scripts.html
{% load static %}
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    new WOW().init();
  </script>